### ISSUE TITLE
Join table

### ISSUE THREAD

**Issue by kephren226** [optimistdigital/nova-input-filter#1]
is there a way to filter according to a belongsTo column ?

**Comment by KasparRosin** [comment]
Yes, here is a simple example.

```
use OptimistDigital\NovaInputFilter\InputFilter;

class BelongsToFilter extends InputFilter
{
    public function apply(Request $request, $query, $search)
    {
        return $query->whereHas('cars', fn ($query) => $query->where('name', 'like', "%$search%"));
    }
}
```

Let me know if this resolves your issue.

**Comment by kephren226** [comment]
Still not working
it seems like the apply function is never call
It just append another condition to the one generated by nova

**Comment by KasparRosin** [comment]
Can you send me a snippet of your filter file.

**Comment by kephren226** [comment]
here it is 

class CptFilter extends InputFilter
{
    /**
     * The filter's component.
     *
     * @var string
     */
    public $component = 'select-filter';

    /**
     * Apply the filter to the given query.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply(Request $request, $query, $search)
    {
        $cpt = Compte::where('numero', 'like', "%$search%")->first();
        return $query->where('id_compte', $cpt->id_compte);
    }

    /**
     * Get the filter's available options.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function options(Request $request)
    {
        return [];
    }
}

**Comment by kephren226** [comment]
And here is how call it 

InputFilter::make(['id_compte'], 'CptFilter'),

**Comment by kephren226** [comment]
Still no idea ?

**Comment by KasparRosin** [comment]
You are not calling the class you've made..

You should call `CptFilter::make([], 'CptFilter)` instead.

**Comment by kephren226** [comment]
What should I pass to n the array ?

**Comment by kephren226** [comment]
I’ll try and be back 
Thanks

**Comment by KasparRosin** [comment]
You should also not override `public $component = 'select-filter'` if you plan to use the input filter.

**Comment by kephren226** [comment]
Thanks 
But i'll leave it for now 
It downgrade certain of my packages when installing
