### ISSUE TITLE
issue when i try to update the composer

### ISSUE THREAD

**Issue by khawala** [optimistdigital/nova-input-filter#5]
Problem 1
    - optimistdigital/nova-input-filter is locked to version 1.1.0 and an update of this package was not requested.
    - optimistdigital/nova-input-filter 1.1.0 requires laravel/nova ^3.0 -> found laravel/nova[3.x-dev (alias of dev-master)] in the lock file and laravel/nova[dev-main] from path repo (./nova) but it does not match your constraint and is therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one from the lock file.

**Comment by Tarpsvo** [comment]
Maybe you have to set ```"minimum-stability": "dev"``` in your composer.json? Seems like you're using some branch other than `laravel/nova 3.0`
