### ISSUE TITLE
dependencies error while installing in Nova 4

### ISSUE THREAD

**Issue by ycoloma-etionic** [optimistdigital/nova-input-filter#8]
im getting the following error 

`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires outl1ne/nova-input-filter ^1.1 -> satisfiable by outl1ne/nova-input-filter[1.1.0].
    - outl1ne/nova-input-filter 1.1.0 requires laravel/nova ^3.0 -> found laravel/nova[dev-master, v3.0.0, ..., 3.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (~4.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

does the package support nova 4?

**Comment by Tarpsvo** [comment]
Nova 4 support added in version 2.0. :)
