### ISSUE TITLE
Is it possible to use this input filter to search for things NOT included?

### ISSUE THREAD

**Issue by vesper8** [optimistdigital/nova-input-filter#9]
Like let's say I want to return all rows that do not contain a word.. so basically the opposite of the default behaviour.

I would find that quite useful!

Thanks!

**Comment by kaareloun** [comment]
It is possible, you need to create a custom filter like described here: https://github.com/outl1ne/nova-input-filter#customizing

So for your example, first make a `NameFilter.php` file:

```
class NameFilter extends InputFilter
{
    public function apply(Request $request, $query, $search)
    {
        return $query->where('name', 'not like', "%$search%");
    }
}
```

and then add it to your resource:

```
public function filters(NovaRequest $request): array
{
    return [
        NameFilter::make(['name'], "Name doesn't contain"),
    ];
}
```
